AS_OLDTONEW = "Attempting to transfer old auctionsnatch data to the new version.  You will not see this message again."
AS_LOADTEXT = "Auction Snatch Loaded.  Type /AS or /auctionsnatch (or /AS prompt)."
AS_NODATA = "No Data"
AS_INTERESTEDIN = "Are you interested in"
AS_BY = "by"
AS_FOR = "for"
AS_BUYOUT = "buyout"
AS_EACH ="each"
AS_BID="bid"
AS_CUTOFF="Cutoff Price for one"


AS_ADDITEM = "Add Item"
AS_START = "Start Search"
AS_STOP = "Stop"
AS_DELETETEXT = "This will delete everything in the current list.  (Requires 'Ctrl' to be held)"
AS_SEARCHTEXT = "Hold Shift as you open the auction house to override this option."
AS_AUTOSEARCH = "Auto Search"
AS_AUTOOPEN = "Auto Open"
AS_DOORBELLTEXT = "I like the soothing doorbell sound.  But you might not."
AS_DOORBELLSOUND = "Doorbell sound"
AS_DELETEROW ="Delete Row"
AS_IMPORT  = "Options"
AS_BUTTONUPDATE = "Update"
AS_BUTTONDELETE = "Delete"
AS_BUTTONIGNORE = "Ignore Item"
AS_BUTTONNEXTAH = "Next in AH"
AS_BUTTONBID = "Bid"
AS_BUTTONCLOSE = "Close"
AS_BUTTONDELETEALL = "Delete All"
AS_BUTTONEXPENSIVE = "Too Expensive"
AS_BUTTONNEXTLIST = "Next in List"
AS_BUTTONBUYOUT = "Buyout"
AS_BUTTONTEXT10 = "Buy this item"
AS_BUTTONTEXT5 = "Bid on this item"
AS_BUTTONTEXT4 = "Go to the next item in the Auction House"
AS_BUTTONTEXT9 = "Go to the next item in your Snatch List"
AS_BUTTONTEXT3 = "Ignore this item with this exact name"
AS_BUTTONTEXT8 = "Ignore this item with this exact name with this buyout price or worse"
AS_BUTTONTEXT2 = "You bought your item - now remove the entry from your list"
AS_BUTTONTEXT7 = "Warning!  This will delete your entire list and reset the UI. (Requires 'Ctrl' held)"
AS_BUTTONTEXT1 = "This is the exact item you were looking for, not that other crap.  Adjust your search to only find this item from now on"
AS_BUTTONTEXT6 = "Close and exit"
AS_INFO ="Drag to re-order, double click to search, right click to snatch"
AS_IGNORECONDITIONS = "Ignore Conditions"
AS_ALWAYS = "Always"
AS_BUTTONCLOSEMANUAL = "Close"
AS_BUTTONEXPENSIVEMANUAL = "Save"
AS_BUTTONIGNOREMANUAL = "Ignore"
AS_BUTTONFILTERS = "Filters"
AS_BUTTONTEXT11 = "Change cutoff price or ignore item"

--I cannot do these.  someone else will have to translate
if ( GetLocale() == "esES" ) then
    AS_OLDTONEW = "Attempting to transfer old auctionsnatch data to the new version.  You will not see this message again."
    AS_LOADTEXT = "Auction Snatch Loaded.  Type /AS or /auctionsnatch (or /AS prompt)."
    AS_NODATA = "No Data"
    AS_INTERESTEDIN = "Are you interested in"
    AS_BY = "by"
    AS_FOR = "for"
    AS_BUYOUT = "buyout"
    AS_EACH ="each"
    AS_BID="bid"
    AS_CUTOFF="Cutoff Price for one"


    AS_ADDITEM = "Add Item"
    AS_START = "Start Search"
    AS_DELETETEXT = "This will delete everything in the current list.  (Requires 'Ctrl' to be held)"
    AS_SEARCHTEXT = "Search automatically when you open the auction house"
    AS_AUTOSEARCH = "Auto Search"
    AS_DOORBELLTEXT = "I like the soothing doorbell sound.  But you might not."
    AS_DOORBELLSOUND = "Doorbell sound?"
    AS_DELETEROW ="Delete Row"
    AS_IMPORT  = "Import List"

    AS_INFO ="Drag to re-order, double click to search"
    AS_IGNORECONDITIONS = "Ignore Conditions"
    AS_ALWAYS = "Always"


elseif ( GetLocale() == "zhTW" ) then
    AS_OLDTONEW = "Attempting to transfer old auctionsnatch data to the new version.  You will not see this message again."
    AS_LOADTEXT = "Auction Snatch Loaded.  Type /AS or /auctionsnatch (or /AS prompt)."
    AS_NODATA = "No Data"
    AS_INTERESTEDIN = "Are you interested in"
    AS_BY = "by"
    AS_FOR = "for"
    AS_BUYOUT = "buyout"
    AS_EACH ="each"
    AS_BID="bid"
    AS_CUTOFF="Cutoff Price for one"


    AS_ADDITEM = "Add Item"
    AS_START = "Start Search"
    AS_DELETETEXT = "This will delete everything in the current list.  (Requires 'Ctrl' to be held)"
    AS_SEARCHTEXT = "Search automatically when you open the auction house"
    AS_AUTOSEARCH = "Auto Search"
    AS_DOORBELLTEXT = "I like the soothing doorbell sound.  But you might not."
    AS_DOORBELLSOUND = "Doorbell sound?"
    AS_DELETEROW ="Delete Row"
    AS_IMPORT  = "Import List"
    
    --[[
    AS_BUTTONNAME1 = "Buyout"
    AS_BUTTONNAME2 = "Bid"
    AS_BUTTONNAME3 = "Next in AH"
    AS_BUTTONNAME4 = "Next in List"
    AS_BUTTONNAME5 = "Ignore Item"
    AS_BUTTONNAME6 = "Too Expensive"
    AS_BUTTONNAME7 = "Delete"
    AS_BUTTONNAME8 = "Delete All"
    AS_BUTTONNAME9 = "Update"
    AS_BUTTONNAME10 = "Close"
    AS_BUTTONTEXT1 = "Buy this item"
    AS_BUTTONTEXT2 = "Bid on this item"
    AS_BUTTONTEXT3 = "Go to the next item in the Auction House"
    AS_BUTTONTEXT4 = "Go to the next item in your Snatch List"
    AS_BUTTONTEXT5 = "Ignore this item with this exact name"
    AS_BUTTONTEXT6 = "Ignore this item with this exact name with this buyout price or worse"
    AS_BUTTONTEXT7 = "You bought your item - now remove the entry from your list"
    AS_BUTTONTEXT8 = "Warning!  This will delete your entire list and reset the UI. (Requires 'Ctrl' held)"
    AS_BUTTONTEXT9 = "This is the exact item you were looking for, not that other crap.  Adjust your search to only find this item from now on"
    AS_BUTTONTEXT10 = "Close and exit"
    ]]
    AS_INFO ="Drag to re-order, double click to search"
    AS_IGNORECONDITIONS = "Ignore Conditions"
    AS_ALWAYS = "Always"



elseif ( GetLocale() == "frFR" ) then
    AS_OLDTONEW = "Tentative de transfer des anciennes informations Auctionsnatch à la nouvelle version. Vous n’allez plus revoir se message."
    AS_LOADTEXT = "Auction Snatch chargé. Tapé /AS ou /auctionsnatch (ou /AS promt)."
    AS_NODATA = "Aucune information."
    AS_INTERESTEDIN = "Est-ce que vous voulez"
    AS_BY = "par"
    AS_FOR = "pour"
    AS_BUYOUT = "Achat immédiat"
    AS_EACH ="chaque"
    AS_BID="Offre"
    AS_CUTOFF="Enlevé le prix pour un"


    AS_ADDITEM = "Ajouté l’objet"
    AS_START = "Commencé la recherche"
    AS_DELETETEXT = "Ceci supprimera tout dans la list. (Vouz devez enfoncer “Ctrl”)"
    AS_SEARCHTEXT = "Recherche automatique quand vous ouvrez la maison d’enchère"
    AS_AUTOSEARCH = "Recherche automatique"
    AS_DOORBELLTEXT = "J’aime bien le son de la sonnette. Peut-être pas vous"
    AS_DOORBELLSOUND = "Sonnette?"
    AS_DELETEROW ="Suprimer la rangée"
    AS_IMPORT  = "Importé la list"
    --[[
    AS_BUTTONNAME1 = "Achat Immédiat"
    AS_BUTTONNAME2 = "Offre"
    AS_BUTTONNAME3 = "Prochaine enchère"
    AS_BUTTONNAME4 = "Prochaine dans la liste"
    AS_BUTTONNAME5 = "Ignoré l'objet"
    AS_BUTTONNAME6 = "Trop chère"
    AS_BUTTONNAME7 = "Supprimer"
    AS_BUTTONNAME8 = "Supprimer tout"
    AS_BUTTONNAME9 = "Mise à jour"
    AS_BUTTONNAME10 = "Fermé"
    AS_BUTTONTEXT1 = "Acheté l’objet"
    AS_BUTTONTEXT2 = "Placé une offre sure l’objet"
    AS_BUTTONTEXT3 = "Allé à l’objet suivant dans la maison."
    AS_BUTTONTEXT4 = "Allé à l’objet suivant dans votre snatch list"
    AS_BUTTONTEXT5 = "Ignoré les objets avec ce nom"
    AS_BUTTONTEXT6 = "Ignoré les objets avec ce nom et avec ce prix d’achat immédiat ou pire"
    AS_BUTTONTEXT7 = "Vous avez acheté l’objet – maintenant enlevé le de votre list."
    AS_BUTTONTEXT8 = "Attention! Ceci supprimera votre list! (Doit garder ‘Ctrl’ enfoncé)"
    AS_BUTTONTEXT9 = "Ceci eest ce que vous recherchiez, pas d’autre merde. Ajusté la recherche pour trouver que cet objet à partir de maintenant"
    AS_BUTTONTEXT10 = "Fermé et quitté"
    ]]
    AS_BUTTONUPDATE = "Update"
    AS_BUTTONDELETE = "Delete"
    AS_BUTTONIGNORE = "Ignore Item"
    AS_BUTTONNEXTAH = "Next in AH"
    AS_BUTTONBID = "Bid"
    AS_BUTTONCLOSE = "Close"
    AS_BUTTONDELETEALL = "Delete All"
    AS_BUTTONEXPENSIVE = "Too Expensive"
    AS_BUTTONNEXTLIST = "Next in List"
    AS_BUTTONBUYOUT = "Buyout"
    
    AS_BUTTONTEXT10 = "Acheté l’objet"
    AS_BUTTONTEXT5 = "Placé une offre sure l’objet"
    AS_BUTTONTEXT4 = "Allé à l’objet suivant dans la maison."
    AS_BUTTONTEXT9 = "Allé à l’objet suivant dans votre snatch list"
    AS_BUTTONTEXT3 = "Ignoré les objets avec ce nom"
    AS_BUTTONTEXT8 = "Ignoré les objets avec ce nom et avec ce prix d’achat immédiat ou pire"
    AS_BUTTONTEXT2 = "Vous avez acheté l’objet – maintenant enlevé le de votre list."
    AS_BUTTONTEXT7 = "Attention! Ceci supprimera votre list! (Doit garder ‘Ctrl’ enfoncé)"
    AS_BUTTONTEXT1 = "Ceci eest ce que vous recherchiez, pas d’autre merde. Ajusté la recherche pour trouver que cet objet à partir de maintenant"
    AS_BUTTONTEXT6 = "Fermé et quitté"

    
    
    AS_INFO ="Traîné pour replacer, double-click pour une recherche."
    AS_IGNORECONDITIONS = "Ignoré les conditions."
    AS_ALWAYS = "Toujours"

end